config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  root 'contacts#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :contact

	validates_presence_of :address, :country
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :addresses, :dependent => :destroy
	has_many :phones, :dependent => :destroy
	accepts_nested_attributes_for :addresses, :phones

	validates_presence_of :first_name, :last_name, :email
	validates :addresses, :phones, :presence => true

	def name
		return first_name+' '+last_name
	end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :contact

	validates_presence_of :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
		@address = @contact.addresses.build
		@phone = @contact.phones.build
	end

	def index
		@contacts = Contact.all
	end

	def create
		@contact = Contact.new(contact_params)
		if address_params[:addresses_attributes].present?
			address_params[:addresses_attributes].each do |key,value|
				@contact.addresses.build(value)
			end
		end
		if phone_params[:phones_attributes].present?
			phone_params[:phones_attributes].each do |key,value|
				@contact.phones.build(value)
			end
		end
		if @contact.save
			redirect_to root_path, notice: 'Contact was successfully created.'
		else
			flash[:error] = @contact.errors.full_messages.to_sentence
			render :new
		end
	end

	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :email)
	end

	def address_params
		params.require(:contact).permit(addresses_attributes: [:address, :country])
	end

	def phone_params
		params.require(:contact).permit(phones_attributes: [:phone])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address.html.erb
<%= f.fields_for :addresses do |builder| %>
	<div class="address-values">
		<%= builder.label :address %>
		<%= builder.text_field :address %> <br>
		<%= builder.label :country %>
		<%= builder.text_field :country %> <br>
	</div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for @contact,  html: {:class => 'form-horizontal'} do |f| %>
	<% if @contact.errors.present?%>
		<div class="alert btn-danger">
			<a href="#" class="close" data-dismiss="alert">×</a>
			<strong>Warning!</strong> <%= @contact.errors.full_messages.to_sentence %>
		</div>
	<% end %>
	<fieldset>
		<legend>Basic Info</legend>
		<div class="form-group">
			<%= f.label :first_name, class: "control-label col-md-2" %>
			<%= f.text_field :first_name,class: "#{@contact.errors.present? && @contact.errors[:first_name].present? ? 'has-error' : ''}" %>
		</div>
		<div class="form-group">
			<%= f.label :last_name, class: 'control-label col-md-2' %>
			<%= f.text_field :last_name %>
		</div>
		<div class="form-group">
			<%= f.label :email, class: 'control-label col-md-2' %>
			<%= f.text_field :email %>
		</div>
		<div class="tab-index">
			<ul class="nav nav-tabs">
				<li role="presentation" class="active"><a href="#address" aria-controls="address" role="tab" data-toggle="tab" aria-expanded="true">Address(s)</a></li>
				<li role="presentation"><a href="#phone" aria-controls="phone" role="tab" data-toggle="tab" aria-expanded="false">Communication Details</a></li>
			</ul>
		</div>
		<div class="tab-content info panel">
			<div role="tabpanel" class="tab-pane active" id="address">
				<%= render :partial => "address", :locals => { :f => f } %> <br>
				<div class="add-address">
					<%= link_to "Add another address", '#', class: 'btn btn-success' %>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="phone">
				<%= render :partial => "phone", :locals => { :f => f } %>
				<div class="add-phone">
					<%= link_to "Add another phone", '#', class: 'btn btn-success' %>
				</div>
			</div>
		</div>
		<div class="actions pull-right">
			<%= link_to "Cancel", root_path, class: 'btn btn-danger' %><%= f.submit 'Create', :class => 'btn btn-success' %>
		</div>
	</fieldset>
<% end %>

app/views/contacts/_phone.html.erb
<%= f.fields_for :phones do |builder| %>
	<div class="phone-values">
		<%= builder.label :phone %>
		<%= builder.text_field :phone %>
	</div>
<% end %>

app/views/contacts/index.html.erb
<% if @contacts.count > 0 %>
	<table class="table table-bordered" style="width:70%">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Primary Address</th>
				<th>Primary Contact</th>
			</tr>
		</thead>
		<tbody>
			<% @contacts.each do |contact| %>
				<tr>
					<td><%= contact.name %></td>
					<td><%= contact.email %></td>
					<td><%= contact.addresses.first.address+'-'+contact.addresses.first.country if contact.addresses.present? %></td>
					<td><%= contact.phones.first.phone if contact.phones.first.present? %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<h3>No contacts created</h3>
	click <%= link_to "here", new_contact_path, method: :get %> to create
<% end %>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<script type="text/javascript">
		<% flash.each do |key, value| %>
			Messenger().post({message: "<%= value.kind_of?(Array) ? value.to_sentence : value %>", type: "<%= key == 'alert' ? 'error' : 'success' %>"});
		<% end %>
	</script>
	<div class="container">
		<header>
			<ul class="nav nav-tabs pull-right">
				<li><%= link_to "All Contacts", root_path %></li>
				<li><%= link_to "New Contact", new_contact_path, method: :get %></li>
			</ul>
			<div class="clearfix"></div>
		</header>
		<%= yield %>
	</div>
</body>
</html>